pipeline {
    agent any

    environment {
        APP_ENV = 'dev'
    }

    stages {
        stage('Clone') {
            steps {
                echo 'Cloning repository...'
                git branch: 'main', url: 'https://github.com/saisai18018/Cap.git'
            }
        }

        stage('Build') {
            steps {
                dir('CapDemo') {
                    echo 'Building the project...'
                    bat 'mvn clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CapDemo') {
                    echo 'Running tests...'
                    bat 'mvn test -Dsurefire.suiteXmlFiles=testng.xml'
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Run App') {
            steps {
                dir('CapDemo') {
                    echo 'Running the Java App...'
                    bat 'java -cp target/CapDemo-0.0.1-SNAPSHOT.jar com.example.App'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying to ${env.APP_ENV} environment..."
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed! Please check logs.'
        }
    }
}
